# [][][][][][][][][][][][][][][][][][][][][]
#  CratesPlus V${project.version}
# [][][][][][][][][][][][][][][][][][][][][]
# ------------------------------------------
# There are many placeholders that can now be used withing the config file for commands and messages, place holders are as followed:
# - %name% - Replaces with the players name, Example: "Notch".
# - %displayname% - Replaces with the players display name, Example: "[Owner] Notch".
# - %uuid% - Replaces with the players UUID.
# - %crate% - The crate types name.
# ------------------------------------------
# Don't change the config version!

Config Version: 3

# Checks if an update is available and notifies staff, uses Spigot
Update Checks: true

# ITEM_NAME-DATA:AMOUNT:CUSTOM_NAME:ENCHANTMENTS|SEPARATED|BY|PIPE|WITH|LEVELS|LIKE|THIS-3
# Commands can be like COMMAND:give %name% 100 coins
# Custom Name can be "NONE" which will use the default item name in Minecraft
# Item name must be a Bukkit material, list here https://hub.spigotmc.org/javadocs/spigot/org/bukkit/material/package-summary.html
Crates:
  Example:
    Items:
    - IRON_SWORD:1:NONE:DAMAGE_ALL-3
    - COOKED_BEEF:32:SUPER BEEF:DAMAGE_ALL-100
    - WOOL-5
    Knockback: 0.5
    Broadcast: false
    Firework: false
    Color: GREEN

# Modify different options of the crate key
Crate Keys:
  Item: TRIPWIRE_HOOK
  Name: "%type% Crate Key"
  Enchantments:
  - DAMAGE_ALL

# If true it will stop players without the admin perm breaking crates
Crate Protection: false

# If true chest will show more info under name hologram
More Info Hologram: true

# Below are all messages that can be edited in the plugin
Messages:
  Prefix: "&7[&bCratesPlus&7]"
  Command No Permission: "&cYou do not have the correct permission to run this command"
  Crate Open Without Key: "&cYou must be holding a %crate% &ckey to open this crate"
  Key Given: "&aYou have been given a %crate% &acrate key"
  Broadcast: "&d%displayname% &dopened a %crate% &dcrate"
  Cant Place: "&cYou can not place crate keys"